### ISSUE TITLE
There are multiple heroes that share the same tag within a subtree

### ISSUE THREAD

**Issue by ammaratef45** [jhontona/animated-floatbuttons#2]
This exception is thrown running your example
Solution: add a unique hero tag as in [this answer](https://stackoverflow.com/a/51359266/5565834)

**Comment by ammaratef45** [comment]
@jhontona you can assign it to me, I'll happily solve it in a PR

**Comment by jhontona** [comment]
Hey! thanks for your help.

**Comment by ammaratef45** [comment]
@jhontona You're welcome, that's paying you back for making the package and save me a lot of time :laughing:
